---

#
# Apt packages
#
- name: Install base packages
  apt: pkg={{item}} update_cache=yes
  with_items:
    - build-essential
    - autoconf
    - automake
    - curl
    - git
    - htop
    - iotop
    - screen
    - vim

- name: Install library dependencies
  apt: pkg={{item}}
  with_items:
    - libffi-dev
    - libjpeg-dev
    - libssl-dev
    - libpng-dev
    - libxml2
    - libxml2-dev
    - libxslt1-dev

#
# Shell and profile setup
#
- name: Vagrant color prompt
  lineinfile:
    dest=/home/vagrant/.bashrc
    regexp="^#? ?force_color_prompt"
    line="force_color_prompt=yes"

- name: Bash script dir
  file:
    path=/home/vagrant/.bash.d
    state=directory
    owner=vagrant
    group=vagrant

- name: User bash profile
  template:
    src=bash_profile.j2
    dest=/home/vagrant/.bash_profile
    owner=vagrant
    group=vagrant
    mode=0644
