---

- name: Add apt repos
  apt_repository: repo="{{item}}"
  with_items: redis_apt_repos

- name: Install packages
  apt: pkg=redis-server={{redis_version}}

- name: Add redis config
  template: src=redis_conf.j2 dest={{redis_config}}

- name: Start all services
  service: name={{item}} state=started
  with_items:
    - redis-server

- name: logrotate
  template: src={{item}}-logrotate.j2 dest=/etc/logrotate.d/{{item}}
  with_items:
    - redis-server
