---

- hosts: all
  user: vagrant
  sudo: yes
  vars:
    postgresql_users:
      - name: vagrant
        pass: ""
        encrypted: no
    postgresql_version: 9.4
  roles:
    - base
    - { role: aeriscloud.rvm }
    - { role: ANXS.nodejs, nodejs_version: "0.12.0", nodejs_install_method: "binary" }
    - { role: ANXS.postgresql }
    - { role: bennojoy.memcached }
    - redis
    - app
